In [1]:
import os
from pathlib import Path

if Path.cwd().name == "notebooks":
    os.chdir("..")

from dementia_speech.io.textgrid import load_word_tier
from dementia_speech.tasks.phonemic_fluency.scoring import score_trial, compute_metrics

In [8]:
textgrid_path = Path("data/raw/textgrids/PFT/PROCESS-2_rec__039__PFT.TextGrid")
df = load_word_tier(textgrid_path)
print(f"Loaded {len(df)} words")
df.head(40)

Loaded 37 words

          word      start        end  duration       iwi
0       Place,   1.855193   2.686355  0.831161       NaN
1         pea,   3.524743   4.160762  0.636019  1.669550
2      potato,   4.818464   5.765265  0.946801  1.293720
3       prune,   6.010999   6.733748  0.722749  1.192536
4        plum,   7.258308   7.923236  0.664929  1.247308
5       peach,   8.942312  10.250488  1.308175  1.684005
6    passport,  11.110559  12.404854  1.294295  2.168247
7       paper,  14.193059  14.944718  0.751659  3.082500
8      purple,  18.107550  19.184446  1.076896  3.914491
9         pink  20.061524  20.827638  0.766114  1.953975
10       polka  22.656193  23.075387  0.419194  2.594668
11        dot,  23.075387  23.595766  0.520379  0.419194
12     parade,  27.237591  28.142591  0.905000  4.162204
13     pastime  28.756927  29.862733  1.105806  1.519336
14        play  30.780624  31.546738  0.766114  2.023697
15   promenade  34.769017  35.817003  1.047986  3.988393
16          mm  38.154912  38.966896  0.811984  3.385895
17       pond,  38.966896  39.775194  0.808298  0.811984
18     people,  42.810739  43.482895  0.672156  3.843843
19     poplar,  45.842886  46.464450  0.621564  3.032147
20          as  46.825824  46.984829  0.159005  0.982938
21          in  46.984829  47.230564  0.245735  0.159005
22       tree,  47.230564  47.714805  0.484242  0.245735
23    popular,  48.119545  49.184602  1.065057  0.888981
24          as  49.184602  49.452019  0.267417  1.065057
25          in  49.452019  49.929034  0.477014  0.267417
26      people  49.929034  50.406048  0.477014  0.477014
27        like  50.406048  50.622872  0.216825  0.477014
28        you,  50.622872  50.859162  0.236289  0.216825
29          um  51.733688  52.737080  1.003392  1.110816
30      plane,  53.597152  54.173835  0.576683  1.863464
31  P-L-A-N-E,  54.173835  55.613382  1.439547  0.576683
32         and  55.613382  55.957732  0.344351  1.439547
33      plain,  55.957732  56.472160  0.514428  0.344351
34  P-L-A-I-N,  56.472160  58.156165  1.684005  0.514428
35          er  59.074056  59.449886  0.375829  2.601896
36      plant.  59.449886  60.180000  0.730114  0.375829

In [9]:
scored_df = score_trial(df, target_letter="p")
scored_df.head(50)

          word      start        end  duration       iwi classification
0       Place,   1.855193   2.686355  0.831161       NaN        correct
1         pea,   3.524743   4.160762  0.636019  1.669550        correct
2      potato,   4.818464   5.765265  0.946801  1.293720        correct
3       prune,   6.010999   6.733748  0.722749  1.192536        correct
4        plum,   7.258308   7.923236  0.664929  1.247308        correct
5       peach,   8.942312  10.250488  1.308175  1.684005        correct
6    passport,  11.110559  12.404854  1.294295  2.168247        correct
7       paper,  14.193059  14.944718  0.751659  3.082500        correct
8      purple,  18.107550  19.184446  1.076896  3.914491        correct
9         pink  20.061524  20.827638  0.766114  1.953975        correct
10       polka  22.656193  23.075387  0.419194  2.594668        correct
11        dot,  23.075387  23.595766  0.520379  0.419194      intrusion
12     parade,  27.237591  28.142591  0.905000  4.162204        correct
13     pastime  28.756927  29.862733  1.105806  1.519336        correct
14        play  30.780624  31.546738  0.766114  2.023697        correct
15   promenade  34.769017  35.817003  1.047986  3.988393        correct
16          mm  38.154912  38.966896  0.811984  3.385895      intrusion
17       pond,  38.966896  39.775194  0.808298  0.811984        correct
18     people,  42.810739  43.482895  0.672156  3.843843        correct
19     poplar,  45.842886  46.464450  0.621564  3.032147        correct
20          as  46.825824  46.984829  0.159005  0.982938      intrusion
21          in  46.984829  47.230564  0.245735  0.159005      intrusion
22       tree,  47.230564  47.714805  0.484242  0.245735      intrusion
23    popular,  48.119545  49.184602  1.065057  0.888981        correct
24          as  49.184602  49.452019  0.267417  1.065057     repetition
25          in  49.452019  49.929034  0.477014  0.267417     repetition
26      people  49.929034  50.406048  0.477014  0.477014        correct
27        like  50.406048  50.622872  0.216825  0.477014      intrusion
28        you,  50.622872  50.859162  0.236289  0.216825      intrusion
29          um  51.733688  52.737080  1.003392  1.110816      intrusion
30      plane,  53.597152  54.173835  0.576683  1.863464        correct
31  P-L-A-N-E,  54.173835  55.613382  1.439547  0.576683        correct
32         and  55.613382  55.957732  0.344351  1.439547      intrusion
33      plain,  55.957732  56.472160  0.514428  0.344351        correct
34  P-L-A-I-N,  56.472160  58.156165  1.684005  0.514428        correct
35          er  59.074056  59.449886  0.375829  2.601896      intrusion
36      plant.  59.449886  60.180000  0.730114  0.375829        correct

In [10]:
scored_df['classification'].value_counts()

classification
correct       25
intrusion     10
repetition     2
Name: count, dtype: int64

In [11]:
metrics = compute_metrics(scored_df)
metrics

{'total_words': 37,
 'correct': 25,
 'intrusions': 10,
 'repetitions': 2,
 'variants': 0,
 'errors': 12}

In [12]:
print("Intrusions:")
print(scored_df[scored_df['classification'] == 'intrusion']['word'].tolist())

print("\nRepetitions:")
print(scored_df[scored_df['classification'] == 'repetition']['word'].tolist())

print("\nVariants:")
print(scored_df[scored_df['classification'] == 'variant']['word'].tolist())

Intrusions:
['dot,', 'mm', 'as', 'in', 'tree,', 'like', 'you,', 'um', 'and', 'er']

Repetitions:
['as', 'in']

Variants:
[]